### ISSUE TITLE
Wikipedia pages/sections that return bad results when queried by begiak

### ISSUE THREAD

**Issue by Leeyp** [apertium/phenny#152]
begiak doesn't work well on these 12 Wikipedia pages and 3 Wikipedia section examples I have found, and these can be generalized into 4 cases as described below. The sample output of the examples can be found in this paste: http://paste2.org/nXM7k8wV
## Case 1: Out of Place Fullstop problem

_Affected URLs_: https://en.wikipedia.org/wiki/Samuel_Johnson
                    https://en.wikipedia.org/wiki/Luca_Pacioli
                    https://en.wikipedia.org/wiki/Retina
                    https://en.wikipedia.org/wiki/Romance_languages
                    https://en.wikipedia.org/wiki/Origin_of_the_name_%22Empire_State%22
            https://en.wikipedia.org/wiki/Capon_Lake_Whipple_Truss_Bridge#Whipple_truss_development
https://ru.wikipedia.org/wiki/Путин,_Владимир_Владимирович
This problem occurs when the article has a period in its first sentence that was not supposed to end the sentence. For example,  periods in "e.g.", "c.", "A.D.", "U.S.", "O.S.", will end begiak/phenny's result prematurely when in the first sentence of the article's description. 
_Example:_<darkgaia> .wik Retina
<begiak> "The retina (/ˈrɛtɪnə/ RET-i-nə, pl" - https://en.wikipedia.org/wiki/Retina
## Case 2: 'NoneType object"

_Affected URLs_: https://en.wikipedia.org/wiki/Main_Page
                    https://en.wikipedia.org/wiki/1990_United_States_Census#State_rankings
https://en.wikipedia.org/wiki/Calendar#Further_reading
This problem appears to occur strikingly on the Main Page, and more commonly in sections, where there is a broad user interface as such, interfering with begiak/phenny's wiki module. 
![image](https://cloud.githubusercontent.com/assets/2010527/11765765/6cc9e5dc-a1a1-11e5-9964-a26a71406eaf.png)
_Example:_<darkgaia> .wik Main_Page
<begiak> AttributeError: 'NoneType' object has no attribute 'text_content' (file "/home/begiak/phenny/modules/wikipedia.py", line 67, in parse_wiki_page)
## Case 3: Right-side extraneous information

_Affected URLs_: https://en.wikipedia.org/wiki/59th_Street_(Manhattan)
                    https://en.wikipedia.org/wiki/East_Harlem
                    https://en.wikipedia.org/wiki/NATO
                    https://en.wikipedia.org/wiki/Broadway_(Manhattan)
This problem occurs strikingly when there are "Coordinates" on the top right hand of an article for a location. However, this appears not to be a problem for some other articles with "Coordinate" information, including https://en.wikipedia.org/wiki/New_York_City, https://en.wikipedia.org/wiki/Chinatown,_Manhattan, https://en.wikipedia.org/wiki/Empire_State_Building. It is unknown what causes this difference in output.
_Example:_<darkgaia> .wik 59th Street (Manhattan)
<begiak> "Coordinates: 40°46′09″N 73°59′05″W﻿ / ﻿40.769212°N 73.984772°W﻿ / 40.769212; -73.984772" - https://en.wikipedia.org/wiki/59th_Street_(Manhattan)
![image](https://cloud.githubusercontent.com/assets/2010527/11765767/7de7c334-a1a1-11e5-9926-5ee240773aa9.png)
![image](https://cloud.githubusercontent.com/assets/2010527/11765768/861cda1c-a1a1-11e5-8f29-ae4079b60add.png)
## Case 4: Non-decriptive First Sentence.

Affected URLs: https://en.wikipedia.org/wiki/Sex_differences_in_humans
This appears to be more of a problem with the article itself than the begiak/phenny module. When the article's first sentence is not descriptive of the article, rather, the description is in the second sentence, a poor result will invariably be returned. 
_Example:_ <darkgaia> .wik Sex differences in humans
<begiak> "Sex differences in humans have been studied in a variety of fields" - https://en.wikipedia.org/wiki/Sex_differences_in_humans

**Comment by wei2912** [comment]
I wonder if we can apply NLP to solve this. :P

**Comment by jonorthwash** [comment]
I wonder what's causing https://en.wikipedia.org/wiki/Aryan and https://en.wikipedia.org/wiki/Indo-Aryan_languages to both return "Pontic Steppe" ....

**Comment by jonorthwash** [comment]
```
(10:33:46) firespeaker: .wik CUNY
(10:33:47) begiak: "Michael P" - https://en.wikipedia.org/wiki/Michael_P._Jacobson
```
It should return https://en.wikipedia.org/wiki/City_University_of_New_York instead, since that's what https://en.wikipedia.org/wiki/CUNY redirects to.

**Comment by jonorthwash** [comment]
> I wonder what's causing https://en.wikipedia.org/wiki/Aryan and https://en.wikipedia.org/wiki/Indo-Aryan_languages to both return "Pontic Steppe" ....

Same for https://en.wikipedia.org/wiki/Saka_language  !!

And `.wik Obama` returns 
`(20:59:26) begiak: "Illinois State SenatorU" - https://en.wikipedia.org/wiki/Barack_Obama`

**Comment by Androbin** [comment]
I can't reproduce Case 2: `NoneType object`

**Comment by Androbin** [comment]
Case 5: Closing bracket in URL is not counted as part of the URL:
`<androbin> .wik 59th Street (Manhattan)`
`<phenny> "Coordinates: 40°46′09″N 73°59′05″W﻿ / ﻿40" - `[`https://en.wikipedia.org/wiki/59th_Street_(Manhattan`](https://en.wikipedia.org/wiki/59th_Street_\(Manhattan)`)`

**Comment by Androbin** [comment]
Can't reproduce issues described by @jonorthwash .

**Comment by Androbin** [comment]
Case 2 fixed by f0b9876ede91f64bf65c9e85de73525c528ed907.

**Comment by jonorthwash** [comment]
Here it seems to be reading from the infobox:
```
(01:44:00) firespeaker: .wik Serbo-Croatian
(01:44:01) begiak: "Institute of Croatian Language and Linguistics (Croatian) Board for Standardization of the Serbian Language (Serbian)" - https://en.wikipedia.org/wiki/Serbo-Croatian
```

**Comment by jonorthwash** [comment]
> Can't reproduce issues described by @jonorthwash .

Which ones specifically?

**Comment by Androbin** [comment]
`.wik CUNY` and `.wik Obama` return expected results for me.

**Comment by jonorthwash** [comment]
I'm still getting this:
```
(23:45:16) firespeaker: .wik Obama
(23:45:18) begiak: "Illinois State Senator U" - https://en.wikipedia.org/wiki/Barack_Obama
```

Perhaps the CUNY one was due to some issue with the page at that time (though I did investigate superficially then and it didn't seem to be).

Also, what about all those other tests I mentioned?  Are you able to reproduce them?

**Comment by Androbin** [comment]
Just realized that I had tested with #316 which also should have gotten rid of the infocard issue.

**Comment by Androbin** [comment]
Either way #320 should resolve all of this.
